# Generated by Django 6.0.4 on 2026-05-07 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('referral_count', models.IntegerField(default=0)),
                ('last_spin', models.DateTimeField(blank=True, null=True)),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rps.botuser')),
            ],
        ),
    ]
