# Generated by Django 6.0.4 on 2026-05-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps', '0002_remove_botuser_last_spin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='botuser',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
