# Generated by Django 6.0.4 on 2026-05-08 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps', '0003_botuser_losses_botuser_wins'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='status',
            field=models.CharField(default='idle', max_length=20),
        ),
        migrations.CreateModel(
            name='GameMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('p1_move', models.CharField(blank=True, max_length=10, null=True)),
                ('p2_move', models.CharField(blank=True, max_length=10, null=True)),
                ('is_with_bot', models.BooleanField(default=False)),
                ('status', models.CharField(default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_p1', to='rps.botuser')),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_p2', to='rps.botuser')),
            ],
        ),
    ]
