# Generated by Django 6.0.4 on 2026-05-12 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps', '0005_cardnumber_depositrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositrequest',
            name='receipt_file_id',
        ),
        migrations.AddField(
            model_name='depositrequest',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name='عکس رسید'),
        ),
        migrations.AlterField(
            model_name='depositrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال'),
        ),
        migrations.AlterField(
            model_name='depositrequest',
            name='status',
            field=models.CharField(choices=[('pending', '⏳ در انتظار بررسی'), ('approved', '✅ تایید شده'), ('rejected', '❌ رد شده')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='depositrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rps.botuser', verbose_name='کاربر'),
        ),
    ]
