# Generated by Django 6.0.4 on 2026-05-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps', '0006_remove_depositrequest_receipt_file_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='last_wheel_spin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
