# Generated by Django 6.0.4 on 2026-05-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps', '0007_botuser_last_wheel_spin'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
