# Generated by Django 6.0.6 on 2026-06-29 17:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps', '0008_botuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoDepositRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=30)),
                ('amount_cents', models.IntegerField(verbose_name='مبلغ (سنت)')),
                ('proof_type', models.CharField(choices=[('screenshot', '📸 اسکرین\u200cشات'), ('tracking', '🔢 کد پیگیری / TxHash')], max_length=15)),
                ('proof_data', models.TextField()),
                ('status', models.CharField(choices=[('pending', '⏳ در انتظار'), ('verified', '✅ تایید شده'), ('rejected', '❌ رد شده')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('accepted', 'پذیرفته شده'), ('rejected', 'رد شده')], default='pending', max_length=10)),
                ('fee_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('ignored', 'نادیده گرفته'), ('banned', 'مسدود شده')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CardNumber',
        ),
        migrations.AlterModelOptions(
            name='botuser',
            options={'ordering': ['-wins']},
        ),
        migrations.RenameField(
            model_name='botuser',
            old_name='balance',
            new_name='total_games',
        ),
        migrations.RenameField(
            model_name='gamematch',
            old_name='is_with_bot',
            new_name='is_offline',
        ),
        migrations.RemoveField(
            model_name='depositrequest',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='gamematch',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='card_number',
        ),
        migrations.AddField(
            model_name='botuser',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سن'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='avatar_file_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='آواتار'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='balance_cents',
            field=models.IntegerField(default=0, verbose_name='موجودی (سنت)'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='botuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تلفن'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='profile_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='botuser',
            name='referral_bonus_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='botuser',
            name='tron_wallet',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس کیف پول ترون'),
        ),
        migrations.AddField(
            model_name='depositrequest',
            name='amount_cents',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamematch',
            name='bet_cents',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamematch',
            name='c4f_board',
            field=models.CharField(default='..........................................', max_length=42),
        ),
        migrations.AddField(
            model_name='gamematch',
            name='c4f_turn',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gamematch',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamematch',
            name='game_type',
            field=models.CharField(choices=[('rps', 'سنگ کاغذ قیچی'), ('ttt', 'دوز'), ('c4f', 'چهار در یک')], default='rps', max_length=5),
        ),
        migrations.AddField(
            model_name='gamematch',
            name='p1_search_msg_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamematch',
            name='search_fee_cents',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamematch',
            name='search_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamematch',
            name='ttt_board',
            field=models.CharField(default='.........', max_length=9),
        ),
        migrations.AddField(
            model_name='gamematch',
            name='ttt_turn',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gamematch',
            name='ttt_winner',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='amount_cents',
            field=models.IntegerField(default=django.utils.timezone.now, verbose_name='مبلغ (سنت)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='tron_wallet',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='آدرس ترون'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='botuser',
            name='status',
            field=models.CharField(default='idle', max_length=200),
        ),
        migrations.AlterField(
            model_name='depositrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='depositrequest',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='depositrequest',
            name='status',
            field=models.CharField(choices=[('pending', '⏳ در انتظار'), ('approved', '✅ تایید شده'), ('rejected', '❌ رد شده')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='depositrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rps.botuser'),
        ),
        migrations.AlterField(
            model_name='gamematch',
            name='p1_move',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gamematch',
            name='p2_move',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gamematch',
            name='status',
            field=models.CharField(choices=[('searching', 'جستجو'), ('active', 'در حال بازی'), ('finished', 'پایان یافته'), ('cancelled', 'لغو شده')], default='searching', max_length=10),
        ),
        migrations.AddField(
            model_name='cryptodepositrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_deposits', to='rps.botuser'),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='rps.botuser'),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='rps.botuser'),
        ),
        migrations.AddField(
            model_name='friendship',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_as_1', to='rps.botuser'),
        ),
        migrations.AddField(
            model_name='friendship',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_as_2', to='rps.botuser'),
        ),
        migrations.AddField(
            model_name='report',
            name='reported',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to='rps.botuser'),
        ),
        migrations.AddField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_sent', to='rps.botuser'),
        ),
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together={('sender', 'receiver')},
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('user1', 'user2')},
        ),
    ]
